In [1]:
import numpy as np

In [5]:
names=np.array(['Bob','Joe','Will','Bob','Joe','Will'])

In [6]:
# 불인참조
names == 'Bob'

array([ True, False, False,  True, False, False])

In [8]:
data=np.random.randn(6,4)
data

array([[-0.17409268,  0.44973632,  0.72708213,  1.40558344],
       [ 0.04962787, -0.54390174, -0.7646908 , -1.67831169],
       [ 0.86570943,  0.03780269, -0.18545774,  0.85138803],
       [-0.91056378,  0.42680113, -0.56392485, -0.70472175],
       [ 1.65236412,  0.67057904,  0.75859357, -0.25422811],
       [-0.34524986, -0.99123634,  0.67968078,  0.66935199]])

In [9]:
data[names=='Bob']
# 행을 기준으로 names=='Bob'의 TRUE, FALSE 결과에 맞춰 TRUE만 출력
# TRUE, FALSE, FALSE, TRUE, FALSE, FALSE이므로 1,4행만 추출

array([[-0.17409268,  0.44973632,  0.72708213,  1.40558344],
       [-0.91056378,  0.42680113, -0.56392485, -0.70472175]])

In [10]:
names[names=='Bob']

array(['Bob', 'Bob'], dtype='<U4')

In [11]:
data

array([[-0.17409268,  0.44973632,  0.72708213,  1.40558344],
       [ 0.04962787, -0.54390174, -0.7646908 , -1.67831169],
       [ 0.86570943,  0.03780269, -0.18545774,  0.85138803],
       [-0.91056378,  0.42680113, -0.56392485, -0.70472175],
       [ 1.65236412,  0.67057904,  0.75859357, -0.25422811],
       [-0.34524986, -0.99123634,  0.67968078,  0.66935199]])

In [12]:
data[names=='Bob', 2:]

array([[ 0.72708213,  1.40558344],
       [-0.56392485, -0.70472175]])

In [13]:
data[names=='Bob', 3]  #벡터 형태로 추출

array([ 1.40558344, -0.70472175])

In [17]:
# 같은 것이 아닐 때, !=  혹은  ~()
names != 'Bob'  #names에 저장된 각각의 자료와 'Bob'을 비교했을 때 같지 않나?
# 혹은
~(names=='Bob')  # ~(비교연산자결과) => 비교연산 결과의 반대

array([False,  True,  True, False,  True,  True])

In [16]:
data[names != 'Bob']

array([[ 0.04962787, -0.54390174, -0.7646908 , -1.67831169],
       [ 0.86570943,  0.03780269, -0.18545774,  0.85138803],
       [ 1.65236412,  0.67057904,  0.75859357, -0.25422811],
       [-0.34524986, -0.99123634,  0.67968078,  0.66935199]])

In [18]:
data[~(names=='Bob')]

array([[ 0.04962787, -0.54390174, -0.7646908 , -1.67831169],
       [ 0.86570943,  0.03780269, -0.18545774,  0.85138803],
       [ 1.65236412,  0.67057904,  0.75859357, -0.25422811],
       [-0.34524986, -0.99123634,  0.67968078,  0.66935199]])

In [19]:
cond = names=='Bob'
cond

array([ True, False, False,  True, False, False])

In [20]:
~cond

array([False,  True,  True, False,  True,  True])

In [21]:
data[~cond]

array([[ 0.04962787, -0.54390174, -0.7646908 , -1.67831169],
       [ 0.86570943,  0.03780269, -0.18545774,  0.85138803],
       [ 1.65236412,  0.67057904,  0.75859357, -0.25422811],
       [-0.34524986, -0.99123634,  0.67968078,  0.66935199]])

In [22]:
# | : or의 의미
(names=='Bob')|(names == 'Will')

array([ True, False,  True,  True, False,  True])

In [23]:
mask = (names=='Bob')|(names == 'Will')
data[mask]  #이름이 밥이거나 윌인 사람의 data추출

array([[-0.17409268,  0.44973632,  0.72708213,  1.40558344],
       [ 0.86570943,  0.03780269, -0.18545774,  0.85138803],
       [-0.91056378,  0.42680113, -0.56392485, -0.70472175],
       [-0.34524986, -0.99123634,  0.67968078,  0.66935199]])

In [24]:
data

array([[-0.17409268,  0.44973632,  0.72708213,  1.40558344],
       [ 0.04962787, -0.54390174, -0.7646908 , -1.67831169],
       [ 0.86570943,  0.03780269, -0.18545774,  0.85138803],
       [-0.91056378,  0.42680113, -0.56392485, -0.70472175],
       [ 1.65236412,  0.67057904,  0.75859357, -0.25422811],
       [-0.34524986, -0.99123634,  0.67968078,  0.66935199]])

In [25]:
data<0

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [False, False,  True, False],
       [ True, False,  True,  True],
       [False, False, False,  True],
       [ True,  True, False, False]])

In [26]:
data[data<0]

array([-0.17409268, -0.54390174, -0.7646908 , -1.67831169, -0.18545774,
       -0.91056378, -0.56392485, -0.70472175, -0.25422811, -0.34524986,
       -0.99123634])

In [27]:
data[data<0]=0

In [28]:
data

array([[0.        , 0.44973632, 0.72708213, 1.40558344],
       [0.04962787, 0.        , 0.        , 0.        ],
       [0.86570943, 0.03780269, 0.        , 0.85138803],
       [0.        , 0.42680113, 0.        , 0.        ],
       [1.65236412, 0.67057904, 0.75859357, 0.        ],
       [0.        , 0.        , 0.67968078, 0.66935199]])

In [29]:
# names에서 이름이 Will이 아닌 사람들에 대한 index를 추출하여
# data 배열의 해당 index 자료값을 모두 10으로 변경하시오.
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Joe', 'Will'], dtype='<U4')

In [31]:
data[names != 'Will']=10
data

array([[10.        , 10.        , 10.        , 10.        ],
       [10.        , 10.        , 10.        , 10.        ],
       [ 0.86570943,  0.03780269,  0.        ,  0.85138803],
       [10.        , 10.        , 10.        , 10.        ],
       [10.        , 10.        , 10.        , 10.        ],
       [ 0.        ,  0.        ,  0.67968078,  0.66935199]])

In [33]:
arr=np.zeros((8,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
arr[1]

array([0., 0., 0., 0.])

In [35]:
#arr[8]   #IndexError : 인덱스 범위를 넘어간 경우 error 발생

IndexError: index 8 is out of bounds for axis 0 with size 8

In [36]:
arr[0]=10

In [37]:
arr

array([[10., 10., 10., 10.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [41]:
for i in range(8):
    arr[i]=i+10

In [42]:
arr

array([[10., 10., 10., 10.],
       [11., 11., 11., 11.],
       [12., 12., 12., 12.],
       [13., 13., 13., 13.],
       [14., 14., 14., 14.],
       [15., 15., 15., 15.],
       [16., 16., 16., 16.],
       [17., 17., 17., 17.]])

In [43]:
# 14가 있는 줄을 출력해보자

arr[4]
# 혹은
arr[arr==14]

array([14., 14., 14., 14.])

In [44]:
arr[[4]]

array([[14., 14., 14., 14.]])

In [46]:
arr[4].shape  #(4,)
arr[[4]].shape  #(1,4)

(1, 4)

In [53]:
arr[4,3]  #14.0, 4행3열 요소값 출력
arr[[4,3]]  #4행과 3행 출력
arr[[4,3,0,6]]  #4행, 3행, 0행 6행의 순서로 출력

array([[14., 14., 14., 14.],
       [13., 13., 13., 13.],
       [10., 10., 10., 10.],
       [16., 16., 16., 16.]])

In [54]:
arr[[-3]]  #뒤에서부터 3번째

array([[15., 15., 15., 15.]])

In [60]:
# 8행 4열 array 생성, 데이터는 10~41까지 저장

arr=np.arange(10,42).reshape(8,4)
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [61]:
# 1,5,7,2 행 추출

arr[[1,5,7,2]]

array([[14, 15, 16, 17],
       [30, 31, 32, 33],
       [38, 39, 40, 41],
       [18, 19, 20, 21]])

In [62]:
arr[[1,5,7,2],[0]]  #1,5,7,2 행의 0번 index의 열만 추출

array([14, 30, 38, 18])

In [64]:
arr[[1,5,7,2],[0,3,1,2]]
# 1인덱스 행에서는 0인덱스 열의 값, 5인덱스 행에서는 3인덱스 열의 값,...
# 이런 식으로 추출하였다
# 1차원으로 추출

array([14, 33, 39, 20])

In [65]:
arr[[1,5,7,2]][:,[0,3,1,2]]
# 1,5,7,2 행에 대해서 0,3,1,2 순서대로 열을 추출

array([[14, 17, 15, 16],
       [30, 33, 31, 32],
       [38, 41, 39, 40],
       [18, 21, 19, 20]])

In [66]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
arr.T  #행과 열이 바뀜

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [68]:
arr.T.shape  #(5,3)

(5, 3)

In [69]:
arr.shape  #(3,5)

(3, 5)

In [70]:
np.dot(arr, arr.T)  #행렬의 곱셈 3행5열 * 5행3열 => 3행 3열

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [74]:
arr=np.arange(10)
arr
np.sqrt(arr) #제곱근
np.exp(arr) #e^(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [75]:
np.random.randn()  #정규분포 따르는 수 내에서 난수 생성

0.8095281066266933

In [76]:
x = np.random.randn(8)
y = np.random.randn(8)

In [77]:
x

array([ 1.83373703,  0.62716497, -0.66820699, -1.03716328,  0.7593502 ,
        0.19913454, -1.12502557, -1.22111442])

In [78]:
y

array([-0.17209528, -0.20649271,  0.00761356,  1.72029874,  0.82987789,
        0.35810407, -0.24425058, -0.8631987 ])

In [79]:
np.maximum(x,y)
# x와 y를 요소마다 비교해서 큰 값을 return

array([ 1.83373703,  0.62716497,  0.00761356,  1.72029874,  0.82987789,
        0.35810407, -0.24425058, -0.8631987 ])

In [80]:
np.minimum(x,y)
# x와 y를 요소마다 비교해서 작은 값을 return

array([-0.17209528, -0.20649271, -0.66820699, -1.03716328,  0.7593502 ,
        0.19913454, -1.12502557, -1.22111442])

In [81]:
arr=np.random.randn(7)*5
arr

array([-10.91240245,   0.04878375,  -3.44598328,   1.31053754,
         6.34728681,   3.50556781, -10.61344207])

In [82]:
np.modf(arr)
# 정수 부분과 소수점 이하 부분이 분리가 되어 출력된다
# () : 튜플
# (array([]), array([])) 형태로 출력됨

(array([-0.91240245,  0.04878375, -0.44598328,  0.31053754,  0.34728681,
         0.50556781, -0.61344207]),
 array([-10.,   0.,  -3.,   1.,   6.,   3., -10.]))

In [86]:
remainder, whole_part = np.modf(arr)

In [87]:
remainder

array([-0.91240245,  0.04878375, -0.44598328,  0.31053754,  0.34728681,
        0.50556781, -0.61344207])

In [88]:
whole_part

array([-10.,   0.,  -3.,   1.,   6.,   3., -10.])

In [89]:
points = np.arange(-5,5,0.01)
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
       -4.4400000e+00, -4.4300000e+00, -4.4200000e+00, -4.4100000e+00,
       -4.4000000e+00, -4.3900000e+00, -4.3800000e+00, -4.3700000e+00,
       -4.3600000e+00, -4.3500000e+00, -4.3400000e+00, -4.3300000e+00,
       -4.3200000e+00, -4.3100000e+00, -4.3000000e+00, -4.2900000e+00,
       -4.2800000e+00, -4.2700000e+00, -4.2600000e+00, -4.2500000e+00,
       -4.2400000e+00, -4.2300000e+00, -4.2200000e+00, -4.2100000e+00,
       -4.2000000e+00, -4.1900000e+00, -4.1800000e+00, -4.1700000e+00,
       -4.1600000e+00, -4.1500000e+00, -4.1400000e+00, -4.1300000e+00,
       -4.1200000e+00, -4.1100000e+00, -4.1000000e+00, -4.0900000e+00,
       -4.0800000e+00, -4.0700000e+00, -4.0600000e+00, -4.0500000e+00,
       -4.0400000e+00, -4.0300000e+00, -4.0200000e+00, -4.0100000e+00,
       -4.0000000e+00, -3.9900000e+00, -3.9800000e+00, -3.9700000e+00,
       -3.9600000e+00, -3.9500000e+00, -3.9400000e+00, -3.9300000e+00,
       -3.9200000e+00, -3.9100000e+00, -3.9000000e+00, -3.8900000e+00,
       -3.8800000e+00, -3.8700000e+00, -3.8600000e+00, -3.8500000e+00,
       -3.8400000e+00, -3.8300000e+00, -3.8200000e+00, -3.8100000e+00,
       -3.8000000e+00, -3.7900000e+00, -3.7800000e+00, -3.7700000e+00,
       -3.7600000e+00, -3.7500000e+00, -3.7400000e+00, -3.7300000e+00,
       -3.7200000e+00, -3.7100000e+00, -3.7000000e+00, -3.6900000e+00,
       -3.6800000e+00, -3.6700000e+00, -3.6600000e+00, -3.6500000e+00,
       -3.6400000e+00, -3.6300000e+00, -3.6200000e+00, -3.6100000e+00,
       -3.6000000e+00, -3.5900000e+00, -3.5800000e+00, -3.5700000e+00,
       -3.5600000e+00, -3.5500000e+00, -3.5400000e+00, -3.5300000e+00,
       -3.5200000e+00, -3.5100000e+00, -3.5000000e+00, -3.4900000e+00,
       -3.4800000e+00, -3.4700000e+00, -3.4600000e+00, -3.4500000e+00,
       -3.4400000e+00, -3.4300000e+00, -3.4200000e+00, -3.4100000e+00,
       -3.4000000e+00, -3.3900000e+00, -3.3800000e+00, -3.3700000e+00,
       -3.3600000e+00, -3.3500000e+00, -3.3400000e+00, -3.3300000e+00,
       -3.3200000e+00, -3.3100000e+00, -3.3000000e+00, -3.2900000e+00,
       -3.2800000e+00, -3.2700000e+00, -3.2600000e+00, -3.2500000e+00,
       -3.2400000e+00, -3.2300000e+00, -3.2200000e+00, -3.2100000e+00,
       -3.2000000e+00, -3.1900000e+00, -3.1800000e+00, -3.1700000e+00,
       -3.1600000e+00, -3.1500000e+00, -3.1400000e+00, -3.1300000e+00,
       -3.1200000e+00, -3.1100000e+00, -3.1000000e+00, -3.0900000e+00,
       -3.0800000e+00, -3.0700000e+00, -3.0600000e+00, -3.0500000e+00,
       -3.0400000e+00, -3.0300000e+00, -3.0200000e+00, -3.0100000e+00,
       -3.0000000e+00, -2.9900000e+00, -2.9800000e+00, -2.9700000e+00,
       -2.9600000e+00, -2.9500000e+00, -2.9400000e+00, -2.9300000e+00,
       -2.9200000e+00, -2.9100000e+00, -2.9000000e+00, -2.8900000e+00,
       -2.8800000e+00, -2.8700000e+00, -2.8600000e+00, -2.8500000e+00,
       -2.8400000e+00, -2.8300000e+00, -2.8200000e+00, -2.8100000e+00,
       -2.8000000e+00, -2.7900000e+00, -2.7800000e+00, -2.7700000e+00,
       -2.7600000e+00, -2.7500000e+00, -2.7400000e+00, -2.7300000e+00,
       -2.7200000e+00, -2.7100000e+00, -2.7000000e+00, -2.6900000e+00,
       -2.6800000e+00, -2.6700000e+00, -2.6600000e+00, -2.6500000e+00,
       -2.6400000e+00, -2.6300000e+00, -2.6200000e+00, -2.6100000e+00,
       -2.6000000e+00, -2.5900000e+00, -2.5800000e+00, -2.5700000e+00,
       -2.5600000e+00, -2.5500000e+00, -2.5400000e+00, -2.5300000e+00,
       -2.5200000e+00, -2.5100000e+00, -2.5000000e+00, -2.4900000e+00,
       -2.4800000e+00, -2.4700000e+00, -2.4600000e+00, -2.4500000e+00,
       -2.4400000e+00, -2.4300000e+00, -2.4200000e+00, -2.4100000e+00,
       -2.4000000e+00, -2.3900000e+00, -2.3800000e+00, -2.3700000e+00,
       -2.3600000e+00, -2.3500000e+00, -2.3400000e+00, -2.3300000e+00,
       -2.3200000e+00, -2.3100000e+00, -2.3000000e+00, -2.2900000e+00,
       -2.2800000e+00, -2.2700000e+00, -2.2600000e+00, -2.2500000e+00,
       -2.2400000e+00, -2.2300000e+00, -2.2200000e+00, -2.2100000e+00,
       -2.2000000e+00, -2.1900000e+00, -2.1800000e+00, -2.1700000e+00,
       -2.1600000e+00, -2.1500000e+00, -2.1400000e+00, -2.1300000e+00,
       -2.1200000e+00, -2.1100000e+00, -2.1000000e+00, -2.0900000e+00,
       -2.0800000e+00, -2.0700000e+00, -2.0600000e+00, -2.0500000e+00,
       -2.0400000e+00, -2.0300000e+00, -2.0200000e+00, -2.0100000e+00,
       -2.0000000e+00, -1.9900000e+00, -1.9800000e+00, -1.9700000e+00,
       -1.9600000e+00, -1.9500000e+00, -1.9400000e+00, -1.9300000e+00,
       -1.9200000e+00, -1.9100000e+00, -1.9000000e+00, -1.8900000e+00,
       -1.8800000e+00, -1.8700000e+00, -1.8600000e+00, -1.8500000e+00,
       -1.8400000e+00, -1.8300000e+00, -1.8200000e+00, -1.8100000e+00,
       -1.8000000e+00, -1.7900000e+00, -1.7800000e+00, -1.7700000e+00,
       -1.7600000e+00, -1.7500000e+00, -1.7400000e+00, -1.7300000e+00,
       -1.7200000e+00, -1.7100000e+00, -1.7000000e+00, -1.6900000e+00,
       -1.6800000e+00, -1.6700000e+00, -1.6600000e+00, -1.6500000e+00,
       -1.6400000e+00, -1.6300000e+00, -1.6200000e+00, -1.6100000e+00,
       -1.6000000e+00, -1.5900000e+00, -1.5800000e+00, -1.5700000e+00,
       -1.5600000e+00, -1.5500000e+00, -1.5400000e+00, -1.5300000e+00,
       -1.5200000e+00, -1.5100000e+00, -1.5000000e+00, -1.4900000e+00,
       -1.4800000e+00, -1.4700000e+00, -1.4600000e+00, -1.4500000e+00,
       -1.4400000e+00, -1.4300000e+00, -1.4200000e+00, -1.4100000e+00,
       -1.4000000e+00, -1.3900000e+00, -1.3800000e+00, -1.3700000e+00,
       -1.3600000e+00, -1.3500000e+00, -1.3400000e+00, -1.3300000e+00,
       -1.3200000e+00, -1.3100000e+00, -1.3000000e+00, -1.2900000e+00,
       -1.2800000e+00, -1.2700000e+00, -1.2600000e+00, -1.2500000e+00,
       -1.2400000e+00, -1.2300000e+00, -1.2200000e+00, -1.2100000e+00,
       -1.2000000e+00, -1.1900000e+00, -1.1800000e+00, -1.1700000e+00,
       -1.1600000e+00, -1.1500000e+00, -1.1400000e+00, -1.1300000e+00,
       -1.1200000e+00, -1.1100000e+00, -1.1000000e+00, -1.0900000e+00,
       -1.0800000e+00, -1.0700000e+00, -1.0600000e+00, -1.0500000e+00,
       -1.0400000e+00, -1.0300000e+00, -1.0200000e+00, -1.0100000e+00,
       -1.0000000e+00, -9.9000000e-01, -9.8000000e-01, -9.7000000e-01,
       -9.6000000e-01, -9.5000000e-01, -9.4000000e-01, -9.3000000e-01,
       -9.2000000e-01, -9.1000000e-01, -9.0000000e-01, -8.9000000e-01,
       -8.8000000e-01, -8.7000000e-01, -8.6000000e-01, -8.5000000e-01,
       -8.4000000e-01, -8.3000000e-01, -8.2000000e-01, -8.1000000e-01,
       -8.0000000e-01, -7.9000000e-01, -7.8000000e-01, -7.7000000e-01,
       -7.6000000e-01, -7.5000000e-01, -7.4000000e-01, -7.3000000e-01,
       -7.2000000e-01, -7.1000000e-01, -7.0000000e-01, -6.9000000e-01,
       -6.8000000e-01, -6.7000000e-01, -6.6000000e-01, -6.5000000e-01,
       -6.4000000e-01, -6.3000000e-01, -6.2000000e-01, -6.1000000e-01,
       -6.0000000e-01, -5.9000000e-01, -5.8000000e-01, -5.7000000e-01,
       -5.6000000e-01, -5.5000000e-01, -5.4000000e-01, -5.3000000e-01,
       -5.2000000e-01, -5.1000000e-01, -5.0000000e-01, -4.9000000e-01,
       -4.8000000e-01, -4.7000000e-01, -4.6000000e-01, -4.5000000e-01,
       -4.4000000e-01, -4.3000000e-01, -4.2000000e-01, -4.1000000e-01,
       -4.0000000e-01, -3.9000000e-01, -3.8000000e-01, -3.7000000e-01,
       -3.6000000e-01, -3.5000000e-01, -3.4000000e-01, -3.3000000e-01,
       -3.2000000e-01, -3.1000000e-01, -3.0000000e-01, -2.9000000e-01,
       -2.8000000e-01, -2.7000000e-01, -2.6000000e-01, -2.5000000e-01,
       -2.4000000e-01, -2.3000000e-01, -2.2000000e-01, -2.1000000e-01,
       -2.0000000e-01, -1.9000000e-01, -1.8000000e-01, -1.7000000e-01,
       -1.6000000e-01, -1.5000000e-01, -1.4000000e-01, -1.3000000e-01,
       -1.2000000e-01, -1.1000000e-01, -1.0000000e-01, -9.0000000e-02,
       -8.0000000e-02, -7.0000000e-02, -6.0000000e-02, -5.0000000e-02,
       -4.0000000e-02, -3.0000000e-02, -2.0000000e-02, -1.0000000e-02,
       -1.0658141e-13,  1.0000000e-02,  2.0000000e-02,  3.0000000e-02,
        4.0000000e-02,  5.0000000e-02,  6.0000000e-02,  7.0000000e-02,
        8.0000000e-02,  9.0000000e-02,  1.0000000e-01,  1.1000000e-01,
        1.2000000e-01,  1.3000000e-01,  1.4000000e-01,  1.5000000e-01,
        1.6000000e-01,  1.7000000e-01,  1.8000000e-01,  1.9000000e-01,
        2.0000000e-01,  2.1000000e-01,  2.2000000e-01,  2.3000000e-01,
        2.4000000e-01,  2.5000000e-01,  2.6000000e-01,  2.7000000e-01,
        2.8000000e-01,  2.9000000e-01,  3.0000000e-01,  3.1000000e-01,
        3.2000000e-01,  3.3000000e-01,  3.4000000e-01,  3.5000000e-01,
        3.6000000e-01,  3.7000000e-01,  3.8000000e-01,  3.9000000e-01,
        4.0000000e-01,  4.1000000e-01,  4.2000000e-01,  4.3000000e-01,
        4.4000000e-01,  4.5000000e-01,  4.6000000e-01,  4.7000000e-01,
        4.8000000e-01,  4.9000000e-01,  5.0000000e-01,  5.1000000e-01,
        5.2000000e-01,  5.3000000e-01,  5.4000000e-01,  5.5000000e-01,
        5.6000000e-01,  5.7000000e-01,  5.8000000e-01,  5.9000000e-01,
        6.0000000e-01,  6.1000000e-01,  6.2000000e-01,  6.3000000e-01,
        6.4000000e-01,  6.5000000e-01,  6.6000000e-01,  6.7000000e-01,
        6.8000000e-01,  6.9000000e-01,  7.0000000e-01,  7.1000000e-01,
        7.2000000e-01,  7.3000000e-01,  7.4000000e-01,  7.5000000e-01,
        7.6000000e-01,  7.7000000e-01,  7.8000000e-01,  7.9000000e-01,
        8.0000000e-01,  8.1000000e-01,  8.2000000e-01,  8.3000000e-01,
        8.4000000e-01,  8.5000000e-01,  8.6000000e-01,  8.7000000e-01,
        8.8000000e-01,  8.9000000e-01,  9.0000000e-01,  9.1000000e-01,
        9.2000000e-01,  9.3000000e-01,  9.4000000e-01,  9.5000000e-01,
        9.6000000e-01,  9.7000000e-01,  9.8000000e-01,  9.9000000e-01,
        1.0000000e+00,  1.0100000e+00,  1.0200000e+00,  1.0300000e+00,
        1.0400000e+00,  1.0500000e+00,  1.0600000e+00,  1.0700000e+00,
        1.0800000e+00,  1.0900000e+00,  1.1000000e+00,  1.1100000e+00,
        1.1200000e+00,  1.1300000e+00,  1.1400000e+00,  1.1500000e+00,
        1.1600000e+00,  1.1700000e+00,  1.1800000e+00,  1.1900000e+00,
        1.2000000e+00,  1.2100000e+00,  1.2200000e+00,  1.2300000e+00,
        1.2400000e+00,  1.2500000e+00,  1.2600000e+00,  1.2700000e+00,
        1.2800000e+00,  1.2900000e+00,  1.3000000e+00,  1.3100000e+00,
        1.3200000e+00,  1.3300000e+00,  1.3400000e+00,  1.3500000e+00,
        1.3600000e+00,  1.3700000e+00,  1.3800000e+00,  1.3900000e+00,
        1.4000000e+00,  1.4100000e+00,  1.4200000e+00,  1.4300000e+00,
        1.4400000e+00,  1.4500000e+00,  1.4600000e+00,  1.4700000e+00,
        1.4800000e+00,  1.4900000e+00,  1.5000000e+00,  1.5100000e+00,
        1.5200000e+00,  1.5300000e+00,  1.5400000e+00,  1.5500000e+00,
        1.5600000e+00,  1.5700000e+00,  1.5800000e+00,  1.5900000e+00,
        1.6000000e+00,  1.6100000e+00,  1.6200000e+00,  1.6300000e+00,
        1.6400000e+00,  1.6500000e+00,  1.6600000e+00,  1.6700000e+00,
        1.6800000e+00,  1.6900000e+00,  1.7000000e+00,  1.7100000e+00,
        1.7200000e+00,  1.7300000e+00,  1.7400000e+00,  1.7500000e+00,
        1.7600000e+00,  1.7700000e+00,  1.7800000e+00,  1.7900000e+00,
        1.8000000e+00,  1.8100000e+00,  1.8200000e+00,  1.8300000e+00,
        1.8400000e+00,  1.8500000e+00,  1.8600000e+00,  1.8700000e+00,
        1.8800000e+00,  1.8900000e+00,  1.9000000e+00,  1.9100000e+00,
        1.9200000e+00,  1.9300000e+00,  1.9400000e+00,  1.9500000e+00,
        1.9600000e+00,  1.9700000e+00,  1.9800000e+00,  1.9900000e+00,
        2.0000000e+00,  2.0100000e+00,  2.0200000e+00,  2.0300000e+00,
        2.0400000e+00,  2.0500000e+00,  2.0600000e+00,  2.0700000e+00,
        2.0800000e+00,  2.0900000e+00,  2.1000000e+00,  2.1100000e+00,
        2.1200000e+00,  2.1300000e+00,  2.1400000e+00,  2.1500000e+00,
        2.1600000e+00,  2.1700000e+00,  2.1800000e+00,  2.1900000e+00,
        2.2000000e+00,  2.2100000e+00,  2.2200000e+00,  2.2300000e+00,
        2.2400000e+00,  2.2500000e+00,  2.2600000e+00,  2.2700000e+00,
        2.2800000e+00,  2.2900000e+00,  2.3000000e+00,  2.3100000e+00,
        2.3200000e+00,  2.3300000e+00,  2.3400000e+00,  2.3500000e+00,
        2.3600000e+00,  2.3700000e+00,  2.3800000e+00,  2.3900000e+00,
        2.4000000e+00,  2.4100000e+00,  2.4200000e+00,  2.4300000e+00,
        2.4400000e+00,  2.4500000e+00,  2.4600000e+00,  2.4700000e+00,
        2.4800000e+00,  2.4900000e+00,  2.5000000e+00,  2.5100000e+00,
        2.5200000e+00,  2.5300000e+00,  2.5400000e+00,  2.5500000e+00,
        2.5600000e+00,  2.5700000e+00,  2.5800000e+00,  2.5900000e+00,
        2.6000000e+00,  2.6100000e+00,  2.6200000e+00,  2.6300000e+00,
        2.6400000e+00,  2.6500000e+00,  2.6600000e+00,  2.6700000e+00,
        2.6800000e+00,  2.6900000e+00,  2.7000000e+00,  2.7100000e+00,
        2.7200000e+00,  2.7300000e+00,  2.7400000e+00,  2.7500000e+00,
        2.7600000e+00,  2.7700000e+00,  2.7800000e+00,  2.7900000e+00,
        2.8000000e+00,  2.8100000e+00,  2.8200000e+00,  2.8300000e+00,
        2.8400000e+00,  2.8500000e+00,  2.8600000e+00,  2.8700000e+00,
        2.8800000e+00,  2.8900000e+00,  2.9000000e+00,  2.9100000e+00,
        2.9200000e+00,  2.9300000e+00,  2.9400000e+00,  2.9500000e+00,
        2.9600000e+00,  2.9700000e+00,  2.9800000e+00,  2.9900000e+00,
        3.0000000e+00,  3.0100000e+00,  3.0200000e+00,  3.0300000e+00,
        3.0400000e+00,  3.0500000e+00,  3.0600000e+00,  3.0700000e+00,
        3.0800000e+00,  3.0900000e+00,  3.1000000e+00,  3.1100000e+00,
        3.1200000e+00,  3.1300000e+00,  3.1400000e+00,  3.1500000e+00,
        3.1600000e+00,  3.1700000e+00,  3.1800000e+00,  3.1900000e+00,
        3.2000000e+00,  3.2100000e+00,  3.2200000e+00,  3.2300000e+00,
        3.2400000e+00,  3.2500000e+00,  3.2600000e+00,  3.2700000e+00,
        3.2800000e+00,  3.2900000e+00,  3.3000000e+00,  3.3100000e+00,
        3.3200000e+00,  3.3300000e+00,  3.3400000e+00,  3.3500000e+00,
        3.3600000e+00,  3.3700000e+00,  3.3800000e+00,  3.3900000e+00,
        3.4000000e+00,  3.4100000e+00,  3.4200000e+00,  3.4300000e+00,
        3.4400000e+00,  3.4500000e+00,  3.4600000e+00,  3.4700000e+00,
        3.4800000e+00,  3.4900000e+00,  3.5000000e+00,  3.5100000e+00,
        3.5200000e+00,  3.5300000e+00,  3.5400000e+00,  3.5500000e+00,
        3.5600000e+00,  3.5700000e+00,  3.5800000e+00,  3.5900000e+00,
        3.6000000e+00,  3.6100000e+00,  3.6200000e+00,  3.6300000e+00,
        3.6400000e+00,  3.6500000e+00,  3.6600000e+00,  3.6700000e+00,
        3.6800000e+00,  3.6900000e+00,  3.7000000e+00,  3.7100000e+00,
        3.7200000e+00,  3.7300000e+00,  3.7400000e+00,  3.7500000e+00,
        3.7600000e+00,  3.7700000e+00,  3.7800000e+00,  3.7900000e+00,
        3.8000000e+00,  3.8100000e+00,  3.8200000e+00,  3.8300000e+00,
        3.8400000e+00,  3.8500000e+00,  3.8600000e+00,  3.8700000e+00,
        3.8800000e+00,  3.8900000e+00,  3.9000000e+00,  3.9100000e+00,
        3.9200000e+00,  3.9300000e+00,  3.9400000e+00,  3.9500000e+00,
        3.9600000e+00,  3.9700000e+00,  3.9800000e+00,  3.9900000e+00,
        4.0000000e+00,  4.0100000e+00,  4.0200000e+00,  4.0300000e+00,
        4.0400000e+00,  4.0500000e+00,  4.0600000e+00,  4.0700000e+00,
        4.0800000e+00,  4.0900000e+00,  4.1000000e+00,  4.1100000e+00,
        4.1200000e+00,  4.1300000e+00,  4.1400000e+00,  4.1500000e+00,
        4.1600000e+00,  4.1700000e+00,  4.1800000e+00,  4.1900000e+00,
        4.2000000e+00,  4.2100000e+00,  4.2200000e+00,  4.2300000e+00,
        4.2400000e+00,  4.2500000e+00,  4.2600000e+00,  4.2700000e+00,
        4.2800000e+00,  4.2900000e+00,  4.3000000e+00,  4.3100000e+00,
        4.3200000e+00,  4.3300000e+00,  4.3400000e+00,  4.3500000e+00,
        4.3600000e+00,  4.3700000e+00,  4.3800000e+00,  4.3900000e+00,
        4.4000000e+00,  4.4100000e+00,  4.4200000e+00,  4.4300000e+00,
        4.4400000e+00,  4.4500000e+00,  4.4600000e+00,  4.4700000e+00,
        4.4800000e+00,  4.4900000e+00,  4.5000000e+00,  4.5100000e+00,
        4.5200000e+00,  4.5300000e+00,  4.5400000e+00,  4.5500000e+00,
        4.5600000e+00,  4.5700000e+00,  4.5800000e+00,  4.5900000e+00,
        4.6000000e+00,  4.6100000e+00,  4.6200000e+00,  4.6300000e+00,
        4.6400000e+00,  4.6500000e+00,  4.6600000e+00,  4.6700000e+00,
        4.6800000e+00,  4.6900000e+00,  4.7000000e+00,  4.7100000e+00,
        4.7200000e+00,  4.7300000e+00,  4.7400000e+00,  4.7500000e+00,
        4.7600000e+00,  4.7700000e+00,  4.7800000e+00,  4.7900000e+00,
        4.8000000e+00,  4.8100000e+00,  4.8200000e+00,  4.8300000e+00,
        4.8400000e+00,  4.8500000e+00,  4.8600000e+00,  4.8700000e+00,
        4.8800000e+00,  4.8900000e+00,  4.9000000e+00,  4.9100000e+00,
        4.9200000e+00,  4.9300000e+00,  4.9400000e+00,  4.9500000e+00,
        4.9600000e+00,  4.9700000e+00,  4.9800000e+00,  4.9900000e+00])

In [90]:
xs, ys = np.meshgrid(points, points)
# 두개의 1차원 배열을 입력받아서 가능한 모든 (x,y) 짝을 만들 수 있는
# 2차원 배열 2개 리턴

In [91]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [93]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [95]:
xs.shape  #(1000, 1000)
ys.shape  #(1000, 1000)

(1000, 1000)

In [97]:
z = np.sqrt(xs**2+ys**2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [99]:
x=np.arange(3)
x

array([0, 1, 2])

In [100]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [101]:
xx, yy = np.meshgrid(x,y)

In [102]:
xx

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [103]:
yy

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [105]:
[list(zip(x,y)) for x,y in zip(xx,yy)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [108]:
xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])

In [109]:
cond=np.array([True, False, True, True, False])

In [112]:
res = [(x if c else y)for x,y,c in zip(xarr, yarr, cond)]
# 만약 c 값이 참이면 x를 거짓이면 y를 취해라
res

[1.1, 2.2, 1.3, 1.4, 2.5]

In [111]:
list(zip(xarr,yarr,cond))

[(1.1, 2.1, True),
 (1.2, 2.2, False),
 (1.3, 2.3, True),
 (1.4, 2.4, True),
 (1.5, 2.5, False)]

In [113]:
xarr

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [114]:
yarr

array([2.1, 2.2, 2.3, 2.4, 2.5])

In [115]:
cond

array([ True, False,  True,  True, False])

In [116]:
np.where(cond, xarr, yarr)
# np.where(조건, 참인 경우, 거짓인 경우)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [120]:
# 4행 4열의 행렬을 randn 함수를 수행한 값으로 초기화
arr = np.random.randn(4,4)
arr

array([[-0.24375217,  0.04510437,  1.52110027,  0.15003692],
       [-0.30753688, -0.46321777, -1.56249499,  0.17535128],
       [-1.10576892,  0.98585661, -1.34998815,  0.77054563],
       [-0.5695906 ,  2.12960339, -0.51919004,  0.38173703]])

In [121]:
# 행렬의 요소값 중에서 1보다 크면 1을 출력, 작으면 0을 출력
np.where(arr>1, 1, 0)

array([[0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0]])

In [122]:
# 행렬의 요소값 중에서 1보다 크면 1을 출력, 작으면 원래 값을 출력
np.where(arr>1, 1, arr)

array([[-0.24375217,  0.04510437,  1.        ,  0.15003692],
       [-0.30753688, -0.46321777, -1.56249499,  0.17535128],
       [-1.10576892,  0.98585661, -1.34998815,  0.77054563],
       [-0.5695906 ,  1.        , -0.51919004,  0.38173703]])

In [124]:
arr=np.random.randn(5,4)
arr

array([[-0.50593726,  0.64306575, -0.40725295, -0.40226591],
       [-0.40183775, -1.37010606, -1.05914757,  0.70479148],
       [ 1.40507544,  0.34598769, -1.01320902, -0.52637377],
       [-1.020937  ,  0.09111224,  1.84459417, -1.96489324],
       [-0.68301001, -1.05875339, -1.24753022,  0.24250804]])

In [127]:
# 평균값 구하기
arr.mean()
# 혹은
np.mean(arr)

-0.31920596766897

In [128]:
arr.sum()

-6.3841193533794005

In [131]:
arr.mean(axis=1)  #col 방향으로 이동해가면서 요소의 평균
arr.sum(axis=1)

array([-0.67239037, -2.1262999 ,  0.21148033, -1.05012384, -2.74678557])

In [132]:
arr.mean(axis=0)  #row 방향으로 이동해가면서 요소의 평균
arr.sum(axis=0)

array([-1.20664657, -1.34869377, -1.8825456 , -1.94623341])

In [137]:
arr = np.arange(1,8)
arr.cumsum()  #누적합

array([ 1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [138]:
arr.cumprod()  #누적곱, 7!=5040(결국 펙토리얼 값을 구하는거나 마찬가지)

array([   1,    2,    6,   24,  120,  720, 5040], dtype=int32)

In [140]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [141]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [144]:
arr.cumsum(axis=0)  #행 방향으로 진행됨에 따라 누적합
arr.cumprod(axis=0)

array([[  1,   2,   3],
       [  4,  10,  18],
       [ 28,  80, 162]], dtype=int32)

In [146]:
arr.cumsum(axis=1)  #열 방향으로 진행됨에 따라 누적합
arr.cumprod(axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]], dtype=int32)

In [147]:
arr = np.random.randn(100)
arr

array([ 0.23225514, -0.29317476,  0.01609862,  0.76543571, -0.65833332,
       -0.06717442,  0.23674823, -0.28576859,  0.18582385, -0.73258365,
       -1.74882298, -0.22613576,  0.23804979, -0.46672475,  0.71692112,
        0.05489617, -1.68411503, -0.75659961, -0.06482771,  0.26134896,
        0.18769958,  0.86723973, -1.06695677,  2.03463641, -0.12992971,
        0.12234133, -0.87265373,  0.50159031,  1.53938037,  0.10641751,
       -0.7842763 , -0.1713761 ,  1.87954884, -1.63920883,  0.15591394,
        1.32788858,  0.6813119 , -1.11261284,  0.00915889,  0.16588181,
        0.46437467, -0.22527057,  0.0845744 ,  0.43484946, -0.53419439,
        0.2097698 ,  1.0384157 , -0.27521636,  1.34791951, -0.24773862,
        1.34742721,  0.60748376, -0.75681092, -1.98902564,  0.33067467,
        0.09822896,  1.07721617,  0.15664113,  0.60573388, -0.45634762,
        0.46394944,  0.89873677, -0.49461968, -1.14237579, -0.21176154,
        1.32602624, -1.20617633, -0.41694793, -1.51838393, -0.12457517,
        0.26308335,  1.6464058 , -1.4448906 ,  0.7665846 , -2.57650795,
        1.2780771 ,  0.80030108, -1.10570629,  0.65273035, -0.89569484,
       -1.370966  , -0.14893039, -0.67818686,  1.84856035, -0.15440625,
       -0.29402621, -0.09500052,  0.72003021, -0.50116686,  0.91021936,
        0.08216163,  0.74374505, -0.05847447, -0.09226183, -0.41853752,
        1.09764903, -1.38339161, -0.57792446,  1.14916062, -1.51892986])

In [148]:
arr.mean()

-0.009384047565030687

In [149]:
arr.std()  #표준편차

0.9055597112927609

In [155]:
# arr에서 양수의 합
(arr>0).sum()  #양수의 개수
arr[arr>0].sum()

51

In [154]:
# arr 최대값, 최소값
print(arr.max())
print(arr.min())

2.0346364109302786
-2.5765079451637503

In [156]:
arr

array([ 0.23225514, -0.29317476,  0.01609862,  0.76543571, -0.65833332,
       -0.06717442,  0.23674823, -0.28576859,  0.18582385, -0.73258365,
       -1.74882298, -0.22613576,  0.23804979, -0.46672475,  0.71692112,
        0.05489617, -1.68411503, -0.75659961, -0.06482771,  0.26134896,
        0.18769958,  0.86723973, -1.06695677,  2.03463641, -0.12992971,
        0.12234133, -0.87265373,  0.50159031,  1.53938037,  0.10641751,
       -0.7842763 , -0.1713761 ,  1.87954884, -1.63920883,  0.15591394,
        1.32788858,  0.6813119 , -1.11261284,  0.00915889,  0.16588181,
        0.46437467, -0.22527057,  0.0845744 ,  0.43484946, -0.53419439,
        0.2097698 ,  1.0384157 , -0.27521636,  1.34791951, -0.24773862,
        1.34742721,  0.60748376, -0.75681092, -1.98902564,  0.33067467,
        0.09822896,  1.07721617,  0.15664113,  0.60573388, -0.45634762,
        0.46394944,  0.89873677, -0.49461968, -1.14237579, -0.21176154,
        1.32602624, -1.20617633, -0.41694793, -1.51838393, -0.12457517,
        0.26308335,  1.6464058 , -1.4448906 ,  0.7665846 , -2.57650795,
        1.2780771 ,  0.80030108, -1.10570629,  0.65273035, -0.89569484,
       -1.370966  , -0.14893039, -0.67818686,  1.84856035, -0.15440625,
       -0.29402621, -0.09500052,  0.72003021, -0.50116686,  0.91021936,
        0.08216163,  0.74374505, -0.05847447, -0.09226183, -0.41853752,
        1.09764903, -1.38339161, -0.57792446,  1.14916062, -1.51892986])

In [159]:
# arr에서 양수는 모두 1로, 음수는 모두 -1로 치환
arr=np.where(arr>0, 1, -1)
arr

array([ 1, -1,  1,  1, -1, -1,  1, -1,  1, -1, -1, -1,  1, -1,  1,  1, -1,
       -1, -1,  1,  1,  1, -1,  1, -1,  1, -1,  1,  1,  1, -1, -1,  1, -1,
        1,  1,  1, -1,  1,  1,  1, -1,  1,  1, -1,  1,  1, -1,  1, -1,  1,
        1, -1, -1,  1,  1,  1,  1,  1, -1,  1,  1, -1, -1, -1,  1, -1, -1,
       -1, -1,  1,  1, -1,  1, -1,  1,  1, -1,  1, -1, -1, -1, -1,  1, -1,
       -1, -1,  1, -1,  1,  1,  1, -1, -1, -1,  1, -1, -1,  1, -1])

In [160]:
bools=np.array([False,False,True,False])

In [161]:
# any : 어느 하나라도 TRUE이면 TRUE 
bools.any()

True

In [162]:
# all : 모두 TRUE이면 TRUE
bools.all()

False

In [163]:
arr=np.random.randn(6)
arr

array([-0.95298803, -0.82669496, -1.15840833,  0.77017191, -1.03728556,
       -1.52320822])

In [164]:
arr.sort()  #오름차순 정렬

In [165]:
arr

array([-1.52320822, -1.15840833, -1.03728556, -0.95298803, -0.82669496,
        0.77017191])

In [166]:
arr=np.random.randn(5,3)
arr

array([[-1.01415183, -1.25379368, -0.47670028],
       [ 0.12796018,  1.77007193, -1.48430679],
       [-0.73339834, -0.23646838,  0.97858205],
       [ 0.1541026 , -0.19771651,  0.15490195],
       [-1.80593952, -1.1200311 ,  0.38753066]])

In [167]:
arr.sort() # 행단위로 열방향으로 정렬시켜 놓음(오름차순)

In [168]:
arr

array([[-1.25379368, -1.01415183, -0.47670028],
       [-1.48430679,  0.12796018,  1.77007193],
       [-0.73339834, -0.23646838,  0.97858205],
       [-0.19771651,  0.1541026 ,  0.15490195],
       [-1.80593952, -1.1200311 ,  0.38753066]])

In [169]:
arr=np.random.randn(5,3)
arr

array([[-0.7915564 , -0.61019896,  0.00145056],
       [ 0.38940199,  0.37288724, -0.10846797],
       [ 0.29965614,  0.51412097,  0.79154619],
       [-0.13530207,  0.62786711, -0.17485552],
       [ 0.68832101,  0.53485521, -0.33211401]])

In [170]:
arr.sort(axis=0)  #열단위로 행방향으로 정렬시켜 놓음(오름차순)

In [171]:
arr

array([[-0.7915564 , -0.61019896, -0.33211401],
       [-0.13530207,  0.37288724, -0.17485552],
       [ 0.29965614,  0.51412097, -0.10846797],
       [ 0.38940199,  0.53485521,  0.00145056],
       [ 0.68832101,  0.62786711,  0.79154619]])

In [173]:
arr=np.array([4,1,7,5,9])
arr

array([4, 1, 7, 5, 9])

In [174]:
arr.sort()
arr

array([1, 4, 5, 7, 9])

In [175]:
arr[::-1]  #numpy는 별도로 내림차순 정렬이 없음
# 오름차순 정렬결과를 뒤에서부터 참조

array([9, 7, 5, 4, 1])

In [176]:
names=np.array(['Bob','Joe','Will','Bob','Joe','Will'])

In [177]:
#np.unique : 유일한 것만 추출
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [179]:
# set으로 추출해도 중복이 제거된다
sorted(set(names))

['Bob', 'Joe', 'Will']

In [180]:
arr=np.array([6,0,0,3,2,5])

In [181]:
np.in1d(arr, [2,3,6])
# arr의 각 원소가 [2,3,6]의 원소에 포함되어 있는지 여부 출력

array([ True, False, False,  True,  True, False])

In [2]:
import numpy as np

In [8]:
a=np.arange(6).reshape(2,3)
len(a) #2, 행의 개수
len(a[0]) #3, 열의 개수
np.shape(a)  #(2,3)
np.shape(a)[0]  #2, 행의 개수
np.shape(a)[1]  #3. 열의 개수

3

In [11]:
# 리스트: 1차원
# 리스트의 리스트: 2차원
# 리스트의 리스트의 리스트: 3차원 배열
d=np.arange(10,34).reshape(2,3,4)
d

array([[[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]],

       [[22, 23, 24, 25],
        [26, 27, 28, 29],
        [30, 31, 32, 33]]])

In [12]:
len(d)  #2, 가장 바깥쪽 대괄호 안에 요소가 2개 있다

2

In [14]:
d[0]  #가장 바깥쪽 대괄호 안의 요소 2개 중 첫번째 요소
len(d[0])  #3

3

In [16]:
d[0][0]
#가장 바깥쪽 대괄호 안의 요소 2개 중 첫번째 요소의 첫번째 요소
len(d[0][0]) #4

4

In [17]:
d.ndim #3

3

In [20]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
# 마지막행의 마지막열 출력
a[-1][-1]

5

In [22]:
x=np.array([1,2])
x.dtype

dtype('int32')

In [23]:
x=np.array([1,2.0])
x.dtype
# 내부적으로 통일이 되기 때문에 int32 -> float64 변환

dtype('float64')

In [24]:
x = np.array([1,2], dtype="f")
x.dtype
# data type을 f 즉, float64로 명시했으므로 이를 인식해서 만든다

dtype('float32')

In [25]:
np.inf #무한대
np.nan #정의할 수 없는 숫자

inf

In [26]:
a=np.array([0,1,-1,0])
b=np.array([1,0,0,0])

In [27]:
a/b  #요소간 연산

<ipython-input-27-aae42d317509>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b
<ipython-input-27-aae42d317509>:1: RuntimeWarning: invalid value encountered in true_divide
  a/b

array([  0.,  inf, -inf,  nan])

In [28]:
np.log(0)

<ipython-input-28-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)

-inf

In [29]:
np.linspace(0,100,5)
#0~100까지 5개의 수를 일정한 구간으로 나누어 출력

array([  0.,  25.,  50.,  75., 100.])

In [34]:
a=np.arange(12)
a.reshape(3,4)
# 혹은
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a
# 2*2*3인 3차원 배열로 reshape을 하고 싶다
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [39]:
# 1차원 배열을 다차원 배열로
a = np.arange(12)
a=a.reshape(2,2,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [43]:
# 다차원 배열을 1차원 배열로
a.reshape(12,)
# 혹은
a.flatten()
# 혹은
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
np.arange(5).shape  #(5,)

(5,)

In [46]:
x=np.arange(5).reshape(1,5)
x.shape  #(1,5)

(1, 5)

In [50]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [52]:
print(x[:,np.newaxis])
print(x[:,np.newaxis].shape)
# 1차원 증가 : np.newaxis => (5,) -> (5,1)

[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)

In [56]:
# stack : 행의 수가 같은 배열을 옆으로 연결(열이 증가)
a = np.ones((2,3))
b = np.zeros((2,2))
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]

In [58]:
# hstack : 좌우로 합치기
np.hstack([a,b])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [60]:
# vstack : 위아래로 합치기
# np.vstack([a,b])  #error, 열의 개수가 맞지 않아서

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [63]:
a=np.ones((2,3))
b=np.zeros((2,3))

np.vstack([a,b])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
a=np.arange(6).reshape(2,3)

In [65]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [67]:
# tile ; 동일한 배열 반복하여 연결
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [70]:
np.tile(a,(3,2))
#위->아래 방향으로 3번, 좌->우 방향으로 2번 반복

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [71]:
x = np.arange(5,14).reshape(3,3)
x

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [76]:
# 기술통계
len(x)  #3
np.mean(x)  #9.0, 평균
np.var(x)  #6.666666667, 분산
np.std(x)  #2.58198889, 표준편차
np.median(x)  #9.0, 중위수

9.0

In [79]:
np.percentile(x,0) #최솟값
np.percentile(x,25)  #1사분위수는 25% 백분위수와 같다
np.percentile(x,50)
np.percentile(x,75)
np.percentile(x,100)

13.0

In [80]:
np.random.seed(111)

In [81]:
np.random.rand(5)  #0이상 1미만 난수

array([0.61217018, 0.16906975, 0.43605902, 0.76926247, 0.2953253 ])

In [82]:
# 셔플함수
x=np.arange(10)
x  #원래는 이렇게 순차적으로 나옴

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.random.shuffle(x)

In [84]:
x  #뒤죽박죽 섞여서 나옴

array([6, 5, 3, 0, 9, 2, 4, 1, 7, 8])

In [86]:
# 데이터 샘플링 함수 프로토타입
# np.random.choice(배열, 크기, replace=복원추출유무, 확률)
arr1=np.arange(11,20)

In [87]:
np.random.choice(arr1, 5)
# 디폴트 값은 replace=True 즉, 복원추출한다(중복되어 뽑는다)

array([13, 16, 17, 19, 16])

In [88]:
np.random.choice(10,5)
# 10은 np.arange(10)을 의미

array([6, 5, 8, 6, 2])

In [89]:
# 확률 주는 경우
np.random.choice(5,5,p=[0.1,0.2,0,0.5,0.2])
# 0이 뽑힐 확률 0.1, 1이 뽑힐 확률 0.2, ...

array([4, 3, 4, 4, 4])

In [95]:
np.random.randint(10)  #0~9 수에서 1개
np.random.randint(5, 10)  #5~9 수에서 1개
np.random.randint(5, 10, size=5)  #5~9 수에서 5개

array([8, 8, 6, 5, 8])

In [96]:
np.unique([1,1,3,3,5])

array([1, 3, 5])

In [100]:
# return_counts=True : 중복되는 것이 몇개 인지 카운트 해줌
x=np.unique([1,1,3,3,5], return_counts=True)
x

(array([1, 3, 5]), array([2, 2, 1], dtype=int64))

In [101]:
x[0]

array([1, 3, 5])

In [103]:
x[1]

array([2, 2, 1], dtype=int64)

In [104]:
idx, cnt = np.unique([1,1,3,3,5], return_counts=True)
print(idx)
print(cnt)

[1 3 5]
[2 2 1]

In [105]:
# 주사위를 5번 던져서 나온 수 집합 = [1,1,3,3,5]
# 1 2 3 4 5 6 이라는 주사위 눈에 대해서 
# 2 0 2 0 1 0 를 결과로 얻고 싶다
np.bincount([1,1,3,3,5], minlength=7)
# bincount는 0부터 센다
# minlength가 7이므로 0~6까지가 카운트 범위가 된다

array([0, 2, 0, 2, 0, 1, 0], dtype=int64)

In [106]:
d=np.bincount([1,1,3,3,5], minlength=7)
d[1:]  #0처리
# 이렇게 처리해주면 우리가 원하던 결과인 것이다.

array([2, 0, 2, 0, 1, 0], dtype=int64)

In [108]:
# 퀴즈
# 난수 생성 -> 로또 생성(1~45)
np.random.randint(1,46, size=6)
np.random.choice(range(1,46), 6, replace=False)

array([21, 45, 23, 20, 31, 16])